AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  GlueIamRole:
    Type: String
    Default: arn:aws:iam::315119964270:role/dl-fmwrk-glue-role
  CodeBucketName:
    Type: String
    Default: dl-fmwrk-code-us-east-2
  DlFmwrkPrefix:
    Type: String
    Default: dl-fmwrk
  ProjectPrefix:
    Type: String
    Default: aws-datalake-framework
  Environment:
    Type: String
    Default: dev
  GlueVersion:
    Type: String
    Default: "3.0"

Resources:
  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Role: !Ref GlueIamRole
      Name: !Sub "${DlFmwrkPrefix}-data-ingestion-${Environment}"
      GlueVersion: !Ref GlueVersion
      Command:
        {
          "Name": "glueetl",
          "ScriptLocation": !Sub "s3://${CodeBucketName}/${Environment}/${ProjectPrefix}-ingestion/ingestion/dataIngestion.py",
        }
      DefaultArguments:
        {
          "--extra-py-files":
            !Sub "s3://${CodeBucketName}/${Environment}/${ProjectPrefix}-ingestion/dependencies/utils.zip,\
            s3://${CodeBucketName}/${Environment}/${ProjectPrefix}-ingestion/dependencies/connector.zip",
          "--extra-files": !Sub "s3://${CodeBucketName}/${Environment}/${ProjectPrefix}-ingestion/ingestion/config/globalConfig.json",
          "--TempDir": !Sub "s3://${CodeBucketName}/temporary/",
          "--additional-python-modules": "psycopg2-binary",
        }
      MaxRetries: 0
      Description: "Perform Data Ingestion"
      AllocatedCapacity: 5
Outputs:
  GlueDataIngestion:
    Description: Latest Commit to be updated here
    Value: !Sub Data Ingestion glue job updated from the latest code in s3://${CodeBucketName}/${Environment}/${ProjectPrefix}-ingestion/ingestion/dataIngestion.py
